const {
  slateDark,
  blueDark,
  greenDark,
  redDark,
  amberDark,
} = require("@radix-ui/colors");

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.vue", "./src/**/*.ts", "./index.html"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "-apple-system",
          "system-ui",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Tahoma",
          "Arial",
          "sans-serif",
        ],
        inter: ["Inter", "sans-serif"],
      },
      keyframes: {
        wiggle: {
          "0%": { transform: "translateX(0)" },
          "15%": { transform: "translateX(0.375rem)" },
          "30%": { transform: "translateX(-0.375rem)" },
          "45%": { transform: "translateX(0.375rem)" },
          "60%": { transform: "translateX(-0.375rem)" },
          "75%": { transform: "translateX(0.375rem)" },
          "90%": { transform: "translateX(-0.375rem)" },
          "100%": { transform: "translateX(0)" },
        },
        "fade-in-up": {
          "0%": { opacity: 0, transform: "translateY(0.5rem)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        shake: {
          "0%, 100%": { transform: "translateX(0)" },
          "25%": { transform: "translateX(0.234375rem)" },
          "50%": { transform: "translateX(-0.234375rem)" },
          "75%": { transform: "translateX(0.234375rem)" },
        },
      },
      animation: {
        wiggle: "wiggle 0.5s ease-in-out",
        "fade-in-up": "fade-in-up 0.3s ease-out",
        shake: "shake 0.3s ease-in-out 0s 2",
      },
    },
    colors: {
      transparent: "transparent",
      white: "#fff",
      current: "currentColor",
      body: slateDark.slate7,
      // Radix-based design system colors
      n: {
        slate: {
          1: "rgb(var(--slate-1) / <alpha-value>)",
          2: "rgb(var(--slate-2) / <alpha-value>)",
          3: "rgb(var(--slate-3) / <alpha-value>)",
          4: "rgb(var(--slate-4) / <alpha-value>)",
          5: "rgb(var(--slate-5) / <alpha-value>)",
          6: "rgb(var(--slate-6) / <alpha-value>)",
          7: "rgb(var(--slate-7) / <alpha-value>)",
          8: "rgb(var(--slate-8) / <alpha-value>)",
          9: "rgb(var(--slate-9) / <alpha-value>)",
          10: "rgb(var(--slate-10) / <alpha-value>)",
          11: "rgb(var(--slate-11) / <alpha-value>)",
          12: "rgb(var(--slate-12) / <alpha-value>)",
        },
        blue: {
          1: "rgb(var(--blue-1) / <alpha-value>)",
          2: "rgb(var(--blue-2) / <alpha-value>)",
          3: "rgb(var(--blue-3) / <alpha-value>)",
          4: "rgb(var(--blue-4) / <alpha-value>)",
          5: "rgb(var(--blue-5) / <alpha-value>)",
          6: "rgb(var(--blue-6) / <alpha-value>)",
          7: "rgb(var(--blue-7) / <alpha-value>)",
          8: "rgb(var(--blue-8) / <alpha-value>)",
          9: "rgb(var(--blue-9) / <alpha-value>)",
          10: "rgb(var(--blue-10) / <alpha-value>)",
          11: "rgb(var(--blue-11) / <alpha-value>)",
          12: "rgb(var(--blue-12) / <alpha-value>)",
        },
        ruby: {
          1: "rgb(var(--ruby-1) / <alpha-value>)",
          2: "rgb(var(--ruby-2) / <alpha-value>)",
          3: "rgb(var(--ruby-3) / <alpha-value>)",
          4: "rgb(var(--ruby-4) / <alpha-value>)",
          5: "rgb(var(--ruby-5) / <alpha-value>)",
          6: "rgb(var(--ruby-6) / <alpha-value>)",
          7: "rgb(var(--ruby-7) / <alpha-value>)",
          8: "rgb(var(--ruby-8) / <alpha-value>)",
          9: "rgb(var(--ruby-9) / <alpha-value>)",
          10: "rgb(var(--ruby-10) / <alpha-value>)",
          11: "rgb(var(--ruby-11) / <alpha-value>)",
          12: "rgb(var(--ruby-12) / <alpha-value>)",
        },
        teal: {
          1: "rgb(var(--teal-1) / <alpha-value>)",
          2: "rgb(var(--teal-2) / <alpha-value>)",
          3: "rgb(var(--teal-3) / <alpha-value>)",
          4: "rgb(var(--teal-4) / <alpha-value>)",
          5: "rgb(var(--teal-5) / <alpha-value>)",
          6: "rgb(var(--teal-6) / <alpha-value>)",
          7: "rgb(var(--teal-7) / <alpha-value>)",
          8: "rgb(var(--teal-8) / <alpha-value>)",
          9: "rgb(var(--teal-9) / <alpha-value>)",
          10: "rgb(var(--teal-10) / <alpha-value>)",
          11: "rgb(var(--teal-11) / <alpha-value>)",
          12: "rgb(var(--teal-12) / <alpha-value>)",
        },
        amber: {
          1: "rgb(var(--amber-1) / <alpha-value>)",
          2: "rgb(var(--amber-2) / <alpha-value>)",
          3: "rgb(var(--amber-3) / <alpha-value>)",
          4: "rgb(var(--amber-4) / <alpha-value>)",
          5: "rgb(var(--amber-5) / <alpha-value>)",
          6: "rgb(var(--amber-6) / <alpha-value>)",
          7: "rgb(var(--amber-7) / <alpha-value>)",
          8: "rgb(var(--amber-8) / <alpha-value>)",
          9: "rgb(var(--amber-9) / <alpha-value>)",
          10: "rgb(var(--amber-10) / <alpha-value>)",
          11: "rgb(var(--amber-11) / <alpha-value>)",
          12: "rgb(var(--amber-12) / <alpha-value>)",
        },
        brand: "#2781F6",
        background: "rgb(var(--background-color) / <alpha-value>)",
        alpha: {
          1: "rgba(var(--alpha-1))",
          2: "rgba(var(--alpha-2))",
          3: "rgba(var(--alpha-3))",
        },
      },
      // Utility colors from radix directly
      slate: {
        ...slateDark,
      },
    },
  },
  plugins: [],
};
